# Generated by Django 2.2 on 2019-07-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
